/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionDB;

/**
 *
 * @author frank
 */
public class AsientoVista extends javax.swing.JFrame {

    /**
     * Creates new form AsientoVista
     */
    public AsientoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAsientosDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle asiento");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(150, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableAsientosDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Concepto", "Debe", "Haber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableAsientosDetalle.setRowHeight(26);
        jScrollPane1.setViewportView(TableAsientosDetalle);
        if (TableAsientosDetalle.getColumnModel().getColumnCount() > 0) {
            TableAsientosDetalle.getColumnModel().getColumn(0).setResizable(false);
            TableAsientosDetalle.getColumnModel().getColumn(0).setPreferredWidth(500);
            TableAsientosDetalle.getColumnModel().getColumn(1).setResizable(false);
            TableAsientosDetalle.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 890, 290));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Transacciones dentro del asiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 880, 50));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/08-cancel.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 310, 60));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 30, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAsientosDetalle;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void generarTabla(String idAsiento) throws SQLException {
        try {
            ConexionDB con = new ConexionDB();
            con.connect();
            ResultSet rs = con.transaccionesPorIdAsiento(idAsiento);
            
            DefaultTableModel dm = (DefaultTableModel) TableAsientosDetalle.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();   
            float debe,haber;
            while (rs.next()){
                if (rs.getBoolean("esDebe")) {
                    debe = rs.getFloat("valor");
                    haber=0f;
                }else {
                    debe = 0f;
                    haber = rs.getFloat("valor");
                }
                dm.addRow(new Object[]{
                    rs.getString("nombre"),
                    debe,              
                    haber
                });
                
            }
            TableAsientosDetalle.setModel(dm);
            getContentPane().repaint();
            con.close();
            
        } catch (Exception e) {
            System.err.println("Problema con la query o algo asi...");
        }
        
    }
}
