/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Frank
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Cuentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NuevaCuenta = new javax.swing.JButton();
        NuevaCuenta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Asiento");
        Principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 322, 97, 23));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cuentas");
        Principal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 330, 97, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/1-asiento.png"))); // NOI18N
        Principal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 235, 102, 81));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/2-cuentas.png"))); // NOI18N
        Principal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 235, -1, 80));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/3-mayores.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Principal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 235, -1, 81));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mayores");
        Principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 322, 97, 23));

        getContentPane().add(Principal, "principal");

        Cuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuentas");
        jLabel1.setToolTipText("");
        Cuentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, 910, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Recibe Saldo", "Tipo", "Editar", "Borrar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Cuentas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1270, 620));

        NuevaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/6-back.png"))); // NOI18N
        NuevaCuenta.setText("Volver");
        NuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCuentaActionPerformed(evt);
            }
        });
        Cuentas.add(NuevaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 50));

        NuevaCuenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/5-add.png"))); // NOI18N
        NuevaCuenta1.setText("Nueva");
        Cuentas.add(NuevaCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1121, 20, 150, 50));

        getContentPane().add(Cuentas, "Cuentas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void NuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuentas;
    private javax.swing.JButton NuevaCuenta;
    private javax.swing.JButton NuevaCuenta1;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
